image: gitlab/dind
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  USER_GITLAB: ProteusDev
  APP_NAME: Bookstore
  REPO: Bookstore

stages:
  - build
  - test
  - docker

maven-build:
  image: maven:latest
  stage: build
  script: "mvnw clean package -B"
  artifacts:
    paths:
      - books/target/*.jar
      - carts/target/*.jar
      - orders/target/*.jar
      - payments/target/*.jar
      - users/target/*.jar

maven-test:
  image: maven:3-jdk-8
  stage: test
  script: "mvnw test"
  artifacts:
    paths:
      - books/target/*.jar
      - carts/target/*.jar
      - orders/target/*.jar
      - payments/target/*.jar
      - users/target/*.jar

docker-build:
  stage: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/ProteusDev/Bookstore .
    - docker push registry.gitlab.com/ProteusDev/Bookstore